- platform: command_line
  switches:
    #bedroom_fan:
    #  command_on: "echo -n -e '\x6d\x6f\x62\x69\x6c\x65\x03\x0d\x0a' | nc -w 1 -u -v -n 10.254.2.249 4000"
    #  command_off: "echo -n -e '\x6d\x6f\x62\x69\x6c\x65\x03\x0d\x0a' | nc -w 1 -u -v -n 10.254.2.249 4000"
    #  #command_state: "echo -n -e '\x6d\x6f\x62\x69\x6c\x65\x01\x0d\x0a' | nc -w 1 -u -n 10.254.2.249 4000 | xxd -ps -l 1 -seek 7"
    #  #value_template: '{{ value == "01" }}'
    livingroom_fan:
      command_on: "python3 custom_scripts/fan_control.py --ip 10.254.2.248 --command power --print power"
      command_off: "python3 custom_scripts/fan_control.py --ip 10.254.2.248 --command power --print power"
      command_state: "python3 custom_scripts/fan_control.py --ip 10.254.2.248 --command status --print power"
      value_template: '{{ value == "01" }}'
