- platform: command_line
  switches:
    bedroom_fan_power:
      command_on: "echo -n -e '\x6d\x6f\x62\x69\x6c\x65\x01\x0d\x0a' | nc -u -v -n 10.254.2.249 4000"
      command_off: "echo -n -e '\x6d\x6f\x62\x69\x6c\x65\x03\x0d\x0a' | nc -u -v -n 10.254.2.249 4000"
    livingroot_fan_power:
      command_on: "echo -n -e '\x6d\x6f\x62\x69\x6c\x65\x01\x0d\x0a' | nc -u -v -n 10.254.2.248 4000"
      command_off: "echo -n -e '\x6d\x6f\x62\x69\x6c\x65\x03\x0d\x0a' | nc -u -v -n 10.254.2.248 4000"
