- platform: command_line
  switches:
    bedroom_fan:
      command_on: "python3 custom_scripts/fan_control.py --ip 10.254.2.249 --command power --print power"
      command_off: "python3 custom_scripts/fan_control.py --ip 10.254.2.249 --command power --print power"
      command_state: "python3 custom_scripts/fan_control.py --ip 10.254.2.249 --command status --print power"
      value_template: '{{ value == "01" }}'
    livingroom_fan:
      command_on: "python3 custom_scripts/fan_control.py --ip 10.254.2.248 --command power --print power"
      command_off: "python3 custom_scripts/fan_control.py --ip 10.254.2.248 --command power --print power"
      command_state: "python3 custom_scripts/fan_control.py --ip 10.254.2.248 --command status --print power"
      value_template: '{{ value == "01" }}'
