language: python
python:
  - "3.7"
install:
  - python3 -m pip install homeassistant
script:
  - hass -c . --script check_config
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - touch zones.yaml
  - touch customize.yaml
