############################################################
#
# Home Assistant Binary Sensors
#
############################################################

- platform: rest
  name: Particle relay reduced heating
  resource: !secret particle_relay1_url
  method: GET
  device_class: cold
  value_template: '{{ value_json.result }}'
  headers:
    User-Agent: Home Assistant
    Content-Type: application/json
#- platform: mqtt
#  state_topic: dummy/floorplan/sensor
#  name: Floorplan

- platform: mqtt
  state_topic: 'smartthings/Bedroom Motion/motion'
  name: 'Motion Sensor Bedroom'
  payload_on: 'active'
  payload_off: 'inactive'
  device_class: motion

- platform: mqtt
  state_topic: 'smartthings/Kitchen Motion/motion'
  name: 'Motion Sensor Kitchen'
  payload_on: 'active'
  payload_off: 'inactive'
  device_class: motion

- platform: mqtt
  state_topic: 'smartthings/Livingroom Motion/motion'
  name: 'Motion Sensor Livingroom'
  payload_on: 'active'
  payload_off: 'inactive'
  device_class: motion

- platform: mqtt
  state_topic: 'smartthings/Cinema Motion/motion'
  name: 'Motion Sensor Cinema'
  payload_on: 'active'
  payload_off: 'inactive'
  device_class: motion

- platform: mqtt
  state_topic: 'smartthings/Entrance/contact'
  name: 'Entrance Contact'
  payload_on: 'open'
  payload_off: 'closed'
  device_class: opening

- platform: mqtt
  state_topic: 'smartthings/Workshop/contact'
  name: 'Workshop Contact'
  payload_on: 'open'
  payload_off: 'closed'
  device_class: opening

- platform: mqtt
  state_topic: 'smartthings/Entrance/acceleration'
  name: 'Entrance Acceleration'
  payload_on: 'active'
  payload_off: 'inactive'
  device_class: moving

- platform: mqtt
  state_topic: 'smartthings/Workshop/acceleration'
  name: 'Workshop Acceleration'
  payload_on: 'active'
  payload_off: 'inactive'
  device_class: moving

- platform: ping
  host: 10.254.2.128
  name: Nintendo Switch

- platform: trend
  sensors:
    bathroom_humidity_falling:
      entity_id: sensor.bathroom_humidity
      friendly_name: Bathroom humidity falling
      sample_duration: 7200
      min_gradient: -0.00138
      device_class: cold
    bathroom_humidity_rising:
      entity_id: sensor.bathroom_humidity
      friendly_name: Bathroom humidity rising
      sample_duration: 7200
      min_gradient: 0.00277
      device_class: moisture
