homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Copenhagen
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret password
  ssl_certificate: /etc/cert/fullchain.pem
  ssl_key: !secret ssl_key
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  base_url: !secret base_url
  #use_x_forwarded_for: True
  #cors_allowed_origins:
  #  - https://google.com
  #  - https://home-assistant.io
  trusted_networks:
    - 127.0.0.1
    - ::1
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
#  ignore:
#    - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

#influxdb:
#  host: 127.0.0.1
#  database: home_assistant
#  username: !secret influxdb_username
#  password: !secret influxdb_password
#  ssl: true
#  verify_ssl: false
#  default_measurement: state
#  blacklist:
#    - entity.id1
#    - entity.id2
#  whitelist:
#    - entity.id3
#    - entity.id4
#  tags:
#    instance: prod
#    source: hass

# The recorder component is storing details in a database which then are handled by the history component.
recorder:
  purge_days: 30

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.bathroom_temerature
      - sensor.bathroom2_temerature
      - sensor.bedroom_temerature
      - sensor.cinema_temerature
      - sensor.kitchen_temerature
      - sensor.livingroom_temerature
    domains:
      - climate

ios:

# Track the sun
sun:

# Text to speech
tts:
  #- platform: google
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: !secret aws_region_name

ifttt:
  key: !secret ifttt_key

tado:
  username: !secret tado_username
  password: !secret tado_password

smappee:
  host: 10.254.2.144
  client_id: !secret smappee_client_id
  client_secret: !secret smappee_client_secret
  username: !secret smappee_username
  password: !secret smappee_password

mqtt:
  broker: 10.254.2.10
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

light:
  platform: hue
  allow_unreachable: true
  allow_hue_groups: true

logger:
  #default: debug
  default: info
  logs:
    pylgtv.webos_client: critical



binary_sensor: !include binary_sensors.yaml
camera: !include cameras.yaml
device_tracker: !include device_trackers.yaml
input_boolean: !include input_boolean.yaml
media_player: !include media_players.yaml
notify: !include notify.yaml
image_processing: !include image_processing.yaml
switch: !include_dir_merge_list switches
script: !include_dir_merge_named scripts
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensors
zone: !include zones.yaml
group: !include groups.yaml
scene: !include scenes.yaml

#zwave:
#  usb_path: /dev/ttyACM0
#  debug: True
#  device_config: !include zwave_device_config.yaml
