homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Copenhagen
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret password
  ssl_certificate: /etc/cert/fullchain.pem
  ssl_key: !secret ssl_key
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  base_url: !secret base_url
  #use_x_forwarded_for: True
  #cors_allowed_origins:
  #  - https://google.com
  #  - https://home-assistant.io
  trusted_networks:
    - 127.0.0.1
    - ::1
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
#  ignore:
#    - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

#influxdb:
#  host: 127.0.0.1
#  database: home_assistant
#  username: !secret influxdb_username
#  password: !secret influxdb_password
#  ssl: true
#  verify_ssl: false
#  default_measurement: state
#  blacklist:
#    - entity.id1
#    - entity.id2
#  whitelist:
#    - entity.id3
#    - entity.id4
#  tags:
#    instance: prod
#    source: hass

# The recorder component is storing details in a database which then are handled by the history component.
recorder:
  purge_days: 30
  db_url: !secret db_url
  exclude:
    domains:
      - climate
    entities:
      - sun.sun
      - sensor.date
      - sensor.cinema_heating
      - sensor.kitchen_heating
      - sensor.bedroom_heating
      - sensor.livingroom_heating
      - sensor.entrance_heating
      - sensor.cinema_temperature
      - sensor.kitchen_temperature
      - sensor.bedroom_temperature
      - sensor.livingroom_temperature
      - sensor.entrance_temperature
      - sensor.cinema_humidity
      - sensor.kitchen_humidity
      - sensor.bedroom_humidity
      - sensor.livingroom_humidity
      - sensor.entrance_humidity
      - sensor.bathroom_link
      - sensor.cinema_link
      - sensor.kitchen_link
      - sensor.bedroom_link
      - sensor.livingroom_link
      - sensor.entrance_link
      - sensor.bathroom_tado_mode
      - sensor.cinema_tado_mode
      - sensor.kitchen_tado_mode
      - sensor.bedroom_tado_mode
      - sensor.livingroom_tado_mode
      - sensor.entrance_tado_mode
      - sensor.ewaldsvej_tado_bridge_status
      - sensor.bathroom_overlay
      - sensor.bathroom_power
      - sensor.cinema_overlay
      - sensor.cinema_power
      - sensor.kitchen_overlay
      - sensor.kitchen_power
      - sensor.bedroom_overlay
      - sensor.bedroom_power
      - sensor.livingroom_overlay
      - sensor.livingroom_power
      - sensor.entrance_overlay
      - sensor.entrance_power
      - sensor.entrance_tilt_x
      - sensor.entrance_tilt_y
      - sensor.entrance_tilt_z
      - sensor.workshop_tilt_x
      - sensor.workshop_tilt_y
      - sensor.workshop_tilt_z
      - binary_sensor.entrance_acceleration
      - binary_sensor.entrance_contact
      - binary_sensor.workshop_acceleration
      - binary_sensor.workshop_contact
      - binary_sensor.motion_sensor_bedroom
      - binary_sensor.motion_sensor_cinema
      - binary_sensor.motion_sensor_kitchen
      - binary_sensor.motion_sensor_livingroom

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.bathroom_temerature
      - sensor.bathroom2_temerature
      - sensor.bedroom_temerature
      - sensor.cinema_temerature
      - sensor.kitchen_temerature
      - sensor.livingroom_temerature
    domains:
      - climate

ios:

# Track the sun
sun:

# Text to speech
#tts:
#  #- platform: google
#  - platform: amazon_polly
#    aws_access_key_id: !secret aws_access_key_id
#    aws_secret_access_key: !secret aws_secret_access_key
#    region_name: !secret aws_region_name

wake_on_lan:

ifttt:
  key: !secret ifttt_key

tado:
  username: !secret tado_username
  password: !secret tado_password

smappee:
  host: 10.254.2.116
  client_id: !secret smappee_client_id
  client_secret: !secret smappee_client_secret
  username: !secret smappee_username
  password: !secret smappee_password

apple_tv:
  host: 10.254.2.108
  login_id: !secret apple_tv_login_id

mqtt:
  broker: 10.254.2.10
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

tradfri:
  host: 10.254.2.102
  api_key: !secret tradfri_api_key

logger:
  #default: debug
  default: info
  logs:
    homeassistant.components.automation: debug
    homeassistant.components.script: debug
    homeassistant.components.device_tracker: critical
    py.warnings: error
  #  pylgtv.webos_client: critical

automation: !include automations.yaml
automation old: !include_dir_merge_list automation

panel_custom: !include panel_custom.yaml

light: !include light.yaml
binary_sensor: !include binary_sensors.yaml
camera: !include cameras.yaml
device_tracker: !include device_trackers.yaml
input_boolean: !include input_boolean.yaml
media_player: !include media_players.yaml
notify: !include notify.yaml
image_processing: !include image_processing.yaml
switch: !include_dir_merge_list switches
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensors
zone: !include zones.yaml
group: !include groups.yaml
scene: !include scenes.yaml

#zwave:
#  usb_path: /dev/ttyACM0
#  debug: True
#  device_config: !include zwave_device_config.yaml
