homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Copenhagen
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

api:

system_health:

# Enables the frontend
frontend:

config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.254.2.10
  #  - 172.16.2.1
  #  - 127.0.0.1
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
    - https://www.home-assistant.io
  trusted_networks:
    - 127.0.0.1
    - ::1
  #ip_ban_enabled: True
  #login_attempts_threshold: 5

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
#  ignore:
#    - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sensor.last_boot
      - sensor.date

#influxdb:
#  host: 127.0.0.1
#  database: home_assistant
#  username: !secret influxdb_username
#  password: !secret influxdb_password
#  ssl: true
#  verify_ssl: false
#  default_measurement: state
#  blacklist:
#    - entity.id1
#    - entity.id2
#  whitelist:
#    - entity.id3
#    - entity.id4
#  tags:
#    instance: prod
#    source: hass
influxdb:
  host: !secret influxdb_host
  port: 8086
  database: home_assistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  tags:
    source: hass

# panel_iframe:
#   grafana:
#     title: Grafana
#     icon: mdi:chart-timeline
#     url: !secret grafana_url
#   influxdb:
#     title: Chronograf
#     icon: mdi:chart-areaspline
#     url: !secret influxdb_url

# The recorder component is storing details in a database which then are handled by the history component.
recorder:
#  db_url: !secret db_url
  exclude:
    domains:
      - climate
      - automation
      - weblink
      - updater
    entities:
      - sensor.bathroom_heating
      - sensor.cinema_heating
      - sensor.kitchen_heating
      - sensor.bedroom_heating
      - sensor.livingroom_heating
      - sensor.entrance_heating
      - sensor.aeotec_dsb05_multisensor_luminance_2
      - sensor.aeotec_dsb05_multisensor_luminance
      - sensor.kitchen_motion_sensor_1
      - sensor.bedroom_motion_sensor_1_2
      - sensor.entrance_motion_sensor_1
      - sensor.bathroom_link
      - sensor.cinema_link
      - sensor.kitchen_link
      - sensor.bedroom_link
      - sensor.livingroom_link
      - sensor.entrance_link
      - sensor.bathroom_tado_mode
      - sensor.cinema_tado_mode
      - sensor.kitchen_tado_mode
      - sensor.bedroom_tado_mode
      - sensor.livingroom_tado_mode
      - sensor.entrance_tado_mode
      - sensor.ewaldsvej_tado_bridge_status
      - sensor.bathroom_overlay
      - sensor.bathroom_power
      - sensor.cinema_overlay
      - sensor.cinema_power
      - sensor.kitchen_overlay
      - sensor.kitchen_power
      - sensor.bedroom_overlay
      - sensor.bedroom_power
      - sensor.livingroom_overlay
      - sensor.livingroom_power
      - sensor.entrance_overlay
      - sensor.entrance_power

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.bathroom_temerature
      - sensor.bathroom2_temerature
      - sensor.bedroom_temerature
      - sensor.cinema_temerature
      - sensor.kitchen_temerature
      - sensor.livingroom_temerature
    domains:
      - climate

cloud:
zeroconf:
ios:
alexa:

# Track the sun
#sun:

# Text to speech
#tts:
#  #- platform: google
#  - platform: amazon_polly
#    aws_access_key_id: !secret aws_access_key_id
#    aws_secret_access_key: !secret aws_secret_access_key
#    region_name: !secret aws_region_name

wake_on_lan:

ifttt:
  key: !secret ifttt_key

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: homeassistant
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

homekit:
  auto_start: True
  filter:
    include_domains:
      - script
      - input_boolean
      - switch
      - light
      - media_player

tado:
  username: !secret tado_username
  password: !secret tado_password

smappee:
  host: 10.254.2.116
  client_id: !secret smappee_client_id
  client_secret: !secret smappee_client_secret
  username: !secret smappee_username
  password: !secret smappee_password

apple_tv:
  host: 10.254.2.195
  login_id: !secret apple_tv_login_id
  credentials: !secret apple_tv_credentials

logi_circle:
  username: !secret logi_circle_username
  password: !secret logi_circle_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# hue:
#   bridges:
#     - host: 10.254.2.105
#       allow_unreachable: true
#       allow_hue_groups: true

#tradfri:
#  host: 10.254.2.102

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

rest_command:
  particle_relay1_on:
    url: !secret particle_relay_post_url
    method: post
    payload: '{ "arg": "relay1:on" }'
    timeout: 5
    content_type: 'application/json'
  particle_relay1_off:
    url: !secret particle_relay_post_url
    method: post
    payload: '{ "arg": "relay1:off" }'
    timeout: 5
    content_type: 'application/json'

logger:
  #default: debug
  #default: info
  default: warning
  logs:
    custom_components.media_player.ps4: debug
    homeassistant.components.smappee: error
    homeassistant.components.mqtt: error
    #homeassistant.deconz: debug
    #homeassistant.components.deconz: debug
    #pydeconz: debug
    py.warnings: error
    pyps4: debug
    smappy: debug
    pyps4.connection: debug
  #  pylgtv.webos_client: critical

automation: !include automations.yaml
automation old: !include_dir_merge_list automation

light: !include light.yaml
binary_sensor: !include binary_sensors.yaml
camera: !include cameras.yaml
device_tracker: !include device_trackers.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
media_player: !include media_players.yaml
notify: !include notify.yaml
image_processing: !include image_processing.yaml
switch: !include_dir_merge_list switches
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensors
zone: !include zones.yaml
group: !include groups.yaml
scene: !include scenes.yaml

#zwave:
#  usb_path: /dev/ttyACM0
#  network_key: !secret zwave_network_key
#  debug: True
