- platform: template
  fans:
    livingroom_fan:
      friendly_name: "Livingroom fan"
      value_template: "{{ states('input_boolean.state') }}"
      speed_template: "{{ states('input_select.bedroom_fan_speed') }}"
      #oscillating_template: "{{ states('input_select.osc') }}"
      direction_template: "{{ states('input_select.bedroom_fan_direction') }}"
      turn_on:
        service: script.livingroom_fan_power
      turn_off:
        service: script.livingroom_fan_power
      set_speed:
        service: shell_command.livingroom_fan_speed
        data_template:
          speed: "{{ speed }}"
      #set_oscillating:
      #  service: script.fan_oscillating
      #  data_template:
      #    oscillating: "{{ oscillating }}"
      set_direction:
        service: shell_command.livingroom_fan_direction
        data_template:
          direction: "{{ direction }}"
      speeds:
        - '00'
        - '01'
        - '02'
