- platform: template
  fans:
    livingroom_fan:
      friendly_name: "Livingroom fan"
      value_template: "{{ states('switch.livingroom_fan') }}"
      speed_template: "{{ states('sensor.livingroom_fan_speed') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.livingroom_fan
      turn_off:
        service: switch.turn_off
        entity_id: switch.livingroom_fan
      set_speed:
        service: shell_command.livingroom_fan_speed
        data_template:
          speed: "{{ speed }}"
      speeds:
        - '01'
        - '02'
        - '03'
