- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen
    - light.kitchen_spot_1
    - light.kitchen_spot_2
    - light.kitchen_spot_3
    - light.kitchen_spot_4
    - light.kitchen_spot_5
    - light.kitchen_spot_6

- platform: group
  name: Entrance Lights
  entities:
    - light.entrance_lamp_1
    - light.entrance_lamp_2
    - light.entrance_lamp_room

- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom
    - light.bedroom_light

- platform: group
  name: Livingroom Lights
  entities:
    - light.livingroom
    - light.gu10_spot1
    - light.gu10_spot2
    - light.gu10_spot3
    - light.lamp_1
    - light.lamp_2
    - light.binic

#- platform: flux_led
#  devices:
#    10.254.2.178:
#      name: stairs
#      mode: "rgb"
#      protocol: ledenet
