- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen
    - light.kitchen_spot_1r1
    - light.kitchen_spot_2r1
    - light.kitchen_spot_3r1
    - light.kitchen_spot_1r2
    - light.kitchen_spot_2r2
    - light.kitchen_spot_3r2

- platform: group
  name: Entrance Lights
  entities:
    - light.entrance_lamp_1
    - light.entrance_lamp_2
    - light.entrance_lamp_room

- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom
    - light.hue_ambiance_ceiling_1

- platform: group
  name: Livingroom Lights
  entities:
    - light.livingroom
    - light.lamp_1
    - light.binic

#- platform: flux_led
#  devices:
#    10.254.2.178:
#      name: stairs
#      mode: "rgb"
#      protocol: ledenet
