############################################################
#
# Home Assistant Media Players
#
############################################################

- platform: plex
#- platform: cast
- platform: denonavr
- platform: webostv
  host: 10.254.2.118
  mac: !secret lg_oled_mac
  name: LG OLED
  customize:
    sources:
    - HDMI2
    - netflix
    - youtube
    - Plex
- platform: ps4
  host: 10.254.2.107
- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret