- platform: template
  sensors:
    template_last_motion:
      friendly_name: 'Last Motion'
      value_template: >
        {%- set sensors = [states.binary_sensor.kitchen_motion_sensor, states.binary_sensor.bedroom_motion_sensor, binary_sensor.sensor_2] %}
        {% for sensor in sensors %}
          {% if as_timestamp(sensor.last_changed) == as_timestamp(sensors | map(attribute='last_changed') | max) %}
            {{ sensor.name }}
          {% endif %}
        {% endfor %}
