- platform: mqtt
  state_topic: 'smartthings/Office/energy'
  name: 'Office energy usage'
  unit_of_measurement: 'kWh'

- platform: mqtt
  state_topic: 'smartthings/Office/power'
  name: 'Office current usage'
  unit_of_measurement: 'W'

- platform: mqtt
  state_topic: 'smartthings/Cinema/illuminance'
  name: 'Cinema light'
  unit_of_measurement: 'lux'

- platform: mqtt
  state_topic: 'smartthings/Serverroom/temperature'
  name: 'Serverroom temperature'
  unit_of_measurement: '°C'

- platform: mqtt
  state_topic: 'smartthings/Entrance/threeAxis'
  name: 'Entrance Tilt X'
  value_template: '{{ value.split(",")[0] }}'
- platform: mqtt
  state_topic: 'smartthings/Entrance/threeAxis'
  name: 'Entrance Tilt Y'
  value_template: '{{ value.split(",")[1] }}'
- platform: mqtt
  state_topic: 'smartthings/Entrance/threeAxis'
  name: 'Entrance Tilt Z'
  value_template: '{{ value.split(",")[2] }}'

- platform: mqtt
  state_topic: 'smartthings/Workshop/threeAxis'
  name: 'Workshop Tilt X'
  value_template: '{{ value.split(",")[0] }}'
- platform: mqtt
  state_topic: 'smartthings/Workshop/threeAxis'
  name: 'Workshop Tilt Y'
  value_template: '{{ value.split(",")[1] }}'
- platform: mqtt
  state_topic: 'smartthings/Workshop/threeAxis'
  name: 'Workshop Tilt Z'
  value_template: '{{ value.split(",")[2] }}'
