- platform: mqtt
  state_topic: 'iotbutton/G030PT033071JFHV'
  name: 'Doorbell'
  value_template: '{{ value_json.clickType }}'
  json_attributes:
    - serialNumber
    - batteryVoltage
    - clickType

- platform: mqtt
  state_topic: 'smartthings/Serverroom/temperature/state'
  name: 'Serverroom temperature'
  unit_of_measurement: 'c'

- platform: mqtt
  state_topic: 'smartthings/Entrance/threeAxis/state'
  name: 'Entrance Tilt X'
  value_template: '{{ value.split(",")[0] }}'
- platform: mqtt
  state_topic: 'smartthings/Entrance/threeAxis/state'
  name: 'Entrance Tilt Y'
  value_template: '{{ value.split(",")[1] }}'
- platform: mqtt
  state_topic: 'smartthings/Entrance/threeAxis/state'
  name: 'Entrance Tilt Z'
  value_template: '{{ value.split(",")[2] }}'

- platform: mqtt
  state_topic: 'smartthings/Workshop/threeAxis/state'
  name: 'Workshop Tilt X'
  value_template: '{{ value.split(",")[0] }}'
- platform: mqtt
  state_topic: 'smartthings/Workshop/threeAxis/state'
  name: 'Workshop Tilt Y'
  value_template: '{{ value.split(",")[1] }}'
- platform: mqtt
  state_topic: 'smartthings/Workshop/threeAxis/state'
  name: 'Workshop Tilt Z'
  value_template: '{{ value.split(",")[2] }}'
