- platform: mqtt
  state_topic: 'iotbutton/G030PT033071JFHV'
  name: 'Doorbell'
  value_template: '{{ value_json.clickType }}'
  json_attributes:
    - serialNumber
    - batteryVoltage
    - clickType
