- alias: "Away Henrik ios"
  trigger:
    - platform: zone
      entity_id: device_tracker.henrik_nicolaisens_iphone
      zone: zone.home
      event: leave
  condition:
    - condition: state
      entity_id: input_boolean.home
      state: 'on'
    - condition: state
      entity_id: input_boolean.force_home_mode
      state: 'off'
  action:
    - service: script.mode_away
