- alias: "Away Henrik ios"
  trigger:
    - platform: zone
      entity_id: device_tracker.henrik_nicolaisens_iphone
      zone: zone.home
      event: leave
  condition:
    - condition: state
      entity_id: input_boolean.home
      state: 'on'
    - condition: time
      after: '1:00'
  action:
    - service: script.mode_away

- alias: "Away Henrik unifi"
  trigger:
    - platform: zone
      entity_id: device_tracker.henrik_nicolaisens_iphone_unifi
      zone: zone.home
      event: leave
  condition:
    - condition: state
      entity_id: input_boolean.home
      state: 'on'
    - condition: time
      after: '1:00'
  action:
    - service: script.mode_away

#- alias: "Away all trackers"
#  trigger:
#    platform: state
#    entity_id: group.all_devices
#    state: 'not_home'
#  action:
#    - service: script.mode_away
