- alias: "Bathroom humidity high"
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_humidity_rising
      to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.bathroom_fan

- alias: "Bathroom humidity normal"
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_humidity_rising
      to: 'off'
      for:
        minutes: 30
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.bathroom_fan

- alias: "Bathroom cold outside"
  trigger:
    - platform: numeric_state
      entity_id: sensor.weather_temperature
      below: 15
  action:
    service: switch.turn_on
    entity_id: switch.bathroom_pump

- alias: "Bathroom heating required"
  trigger:
    - platform: numeric_state
      entity_id: sensor.bathroom_heating
      above: 0
  action:
    service: switch.turn_on
    entity_id: switch.bathroom_pump

- alias: "Bathroom heating ok"
  trigger:
    - platform: state
      entity_id: sensor.bathroom_heating
      to: '0.0'
      for:
        minutes: 30
  condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      above: 15
  action:
    service: switch.turn_off
    entity_id: switch.bathroom_pump

