- alias: Low Battery Notification
  hide_entity: True
  trigger:
    - platform: template
      value_template: >
        {% for zwave in states.zwave if zwave.attributes.battery_level %}
          {%- if zwave.attributes.battery_level | int < 60 -%}
            {{true}}
          {%- endif -%}
        {%- endfor -%}
  action:
    - service: notify.all
      data_template:
        message: >
          {{ trigger.to_state.attributes.friendly_name }} needs new batteries.