- alias: "AWS IOT doorbell"
  trigger:
    platform: webhook
    webhook_id: asdf234fvsd89fh23f98g7sda87fq74o8rgasd87fgwqe87rg8as7gdf
  action:
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
      value: '{{ trigger.event.data.value }}'
