- alias: "Henrik is Home"
  trigger:
    - platform: zone
      entity_id: device_tracker.henrik_nicolaisens_iphone
      zone: zone.home
      event: enter
    - platform: state
      entity_id: device_tracker.henrik_nicolaisens_iphone
      state: 'home'
  action:
    - service: script.mode_home
