- alias: "Home"
  trigger:
    - platform: state
      entity_id: group.all_devices
      state: 'home'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'home'
  action:
    - service: script.mode_home
    - service: notify.all
      data:
        message: "Welcome home"

- alias: "Home zone ios"
  trigger:
    - platform: zone
      entity_id: device_tracker.henrik_nicolaisens_iphone
      zone: zone.home
      event: enter
  action:
    - service: script.mode_home
    - service: notify.all
      data:
        message: "Welcome home"

- alias: "Home zone locative"
  trigger:
    - platform: zone
      entity_id: device_tracker.10d901cf25914a4087a11148ef4ad9b9
      zone: zone.home
      event: enter
  action:
    - service: script.mode_home
    - service: notify.all
      data:
        message: "Welcome home"
