- alias: "Face detection found Henrik"
  trigger:
    platform: event
    event_type: image_processing.detect_face
    event_data:
      entity_id: image_processing.dlib_face_outside_2
      name: 'Henrik'
  condition:
    - condition: template
      value_template: "{% if not is_state('device_tracker.henrik_nicolaisens_iphone', 'home') %}true{% endif %}"
  action:
    - service: script.mode_home

- alias: "Face detection found person"
  trigger:
    platform: event
    event_type: image_processing.detect_face
    event_data:
      entity_id: image_processing.dlib_face_outside
  action:
    - service: script.face_all
