- alias: "Motion in Kitchen"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_kitchen
      to: 'on'
    - platform: state
      entity_id: binary_sensor.entrance_multisensor_motion
      to: 'on'
  condition:
#    - condition: sun
#      after: sunset
#      after_offset: "-1:00:00"
    - condition: state
      entity_id: input_boolean.sleep
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_on

- alias: "Motion stopped in Kitchen"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_kitchen
      to: 'off'
      for:
        minutes: 2
    - platform: state
      entity_id: binary_sensor.entrance_multisensor_motion
      to: 'off'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: binary_sensor.motion_sensor_kitchen
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_off

# - alias: "Motion stopped in Kitchen but light is on"
#   trigger:
#     - platform: state
#       entity_id: light.kitchen
#       to: 'on'
#       for:
#         minutes: 2
#   condition:
#     - condition: state
#       entity_id: binary_sensor.motion_sensor_kitchen
#       state: 'off'
#       for:
#         minutes: 2
#   action:
#     service: scene.turn_on
#     entity_id: scene.kitchen_off

- alias: "Motion in Bedroom"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_bedroom
      to: 'on'
  condition:
#    - condition: sun
#      after: sunset
#      after_offset: "-1:00:00"
    - condition: state
      entity_id: input_boolean.sleep
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_on

- alias: "Motion stopped in Bedroom"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_bedroom
      to: 'off'
      for:
        minutes: 2
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_off

# - alias: "Motion anywhere at night"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.motion_sensor_kitchen
#       to: 'on'
#     - platform: state
#       entity_id: binary_sensor.motion_sensor_bedroom
#       to: 'on'
#     - platform: state
#       entity_id: binary_sensor.motion_sensor_cinema
#       to: 'on'
#     - platform: state
#       entity_id: binary_sensor.motion_sensor_livingroom
#       to: 'on'
#   condition:
#     - condition: sun
#       after: sunset
#       after_offset: "-1:00:00"
#     - condition: state
#       entity_id: input_boolean.sleep
#       state: 'off'
#   action:
#     - service: light.hue_activate_scene
#       data:
#         group_name: "Cinema"
#         scene_name: "TV"

# - alias: "Motion anywhere when in sleep mode"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.motion_sensor_kitchen
#       to: 'on'
#     - platform: state
#       entity_id: binary_sensor.motion_sensor_cinema
#       to: 'on'
#     - platform: state
#       entity_id: binary_sensor.motion_sensor_livingroom
#       to: 'on'
#   condition:
#     - condition: state
#       entity_id: input_boolean.sleep
#       state: 'on'
#   action:
#     - service: light.hue_activate_scene
#       data:
#         group_name: "Cinema"
#         scene_name: "Nightlight"

# - alias: "Motion stopped in sleep mode"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.motion_sensor_kitchen
#       to: 'off'
#     - platform: state
#       entity_id: binary_sensor.motion_sensor_cinema
#       to: 'off'
#     - platform: state
#       entity_id: binary_sensor.motion_sensor_livingroom
#       to: 'off'
#   condition:
#     - condition: state
#       entity_id: input_boolean.sleep
#       state: 'on'
#     - condition: state
#       entity_id: binary_sensor.motion_sensor_kitchen
#       state: 'off'
#       for:
#         minutes: 5
#     - condition: state
#       entity_id: binary_sensor.motion_sensor_cinema
#       state: 'off'
#       for:
#         minutes: 5
#     - condition: state
#       entity_id: binary_sensor.motion_sensor_livingroom
#       state: 'off'
#       for:
#         minutes: 5
#   action:
#     service: scene.turn_on
#     entity_id: scene.sleep
