- alias: "Motion in Kitchen"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_kitchen
      state: 'on'
  condition:
#    - condition: sun
#      after: sunset
#      after_offset: "-1:00:00"
    - condition: state
      entity_id: input_boolean.sleep
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_on

- alias: "Motion stopped in Kitchen"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_kitchen
      state: 'off'
      for:
        minutes: 2
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_off

- alias: "Motion stopped in Kitchen but light is on"
  trigger:
    - platform: state
      entity_id: light.kitchen
      state: 'on'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: binary_sensor.motion_sensor_kitchen
      state: 'off'
      for:
        minutes: 2
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_off

- alias: "Motion in Bedroom"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_bedroom
      state: 'on'
  condition:
#    - condition: sun
#      after: sunset
#      after_offset: "-1:00:00"
    - condition: state
      entity_id: input_boolean.sleep
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_on

- alias: "Motion stopped in Bedroom"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_bedroom
      state: 'off'
      for:
        minutes: 2
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_off

- alias: "Motion anywhere at night"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_kitchen
      state: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_bedroom
      state: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_cinema
      state: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_livingroom
      state: 'on'
  condition:
    - condition: sun
      after: sunset
      after_offset: "-1:00:00"
    - condition: state
      entity_id: input_boolean.sleep
      state: 'off'
  action:
    - service: light.hue_activate_scene
      data:
        group_name: "Cinema"
        scene_name: "Tropical twilight"

- alias: "Motion anywhere when in sleep mode"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_kitchen
      state: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_cinema
      state: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_livingroom
      state: 'on'
  condition:
    - condition: sun
      after: sunset
      after_offset: "-1:00:00"
    - condition: state
      entity_id: input_boolean.sleep
      state: 'on'
  action:
    - service: light.hue_activate_scene
      data:
        group_name: "Cinema"
        scene_name: "Nightlight"

- alias: "Motion stopped in sleep mode"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_kitchen
      state: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.motion_sensor_cinema
      state: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.motion_sensor_livingroom
      state: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.sleep
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.sleep
