- alias: "IKEA remote control turn on lights"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 1002
  condition:
    - condition: state
      entity_id: light.entrance_light_1
      state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: all.lights
      brightness: 255

- alias: "IKEA remote control turn off lights"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 1002
  condition:
    - condition: state
      entity_id: light.entrance_light_1
      state: 'on'
  action:
    service: light.turn_off
    data:
      entity_id: all.lights

- alias: "Cinema remote control turn on lights"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: cinema_dimmer_switch
        event: 1002
  action:
    service: light.turn_on
    data:
      entity_id: light.kitchen_lights
      brightness: 255

- alias: "Cinema remote control turn off lights"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: cinema_dimmer_switch
        event: 4002
  action:
    service: light.turn_off
    data:
      entity_id: light.all.lights
