# - alias: "Smoke detected in Kitchen"
#   trigger:
#     - platform: state
#       entity_id: sensor.kitchen_nest_protect_smoke_status
#       from: 'Ok'
#   action:
#     - service: notify.all
#       data:
#         message: "Smoke detected in the Kitchen!"
#     - service: light.turn_on
#       data:
#         entity_id: group.all_lights
#         brightness: 255

- alias: "Smoke detected by fibaro sensor"
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgss101_smoke_sensor_smoke
    to: '255'
  action:
    - service: notify.all
      data:
        message: "Smoke detected by fibaro sensor!"
    - service: light.turn_on
      data:
        entity_id: group.all_lights
        brightness: 255

- alias: "Smoke cleared by fibaro sensor"
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgss101_smoke_sensor_smoke
    to: '0'
    from: '255'
  action:
    service: notify.all
    data:
      message: "Smoke cleared from fibaro sensor"

- alias: "Smoke sensor opened"
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgss101_smoke_sensor_general
    from: '0'
    to: '255'
  action:
    - service: notify.all
      data:
        message: "Fibaro Smoke Sensor - Cover Opened"

- alias: "Smoke sensor closed"
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgss101_smoke_sensor_general
    to: '0'
    from: '255'
  action:
    - service: notify.all
      data:
        message: "Fibaro Smoke Sensor - Cover Closed"
