- alias: Smoke Sensor SMOKE
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgss101_smoke_sensor_smoke
    to: '255'
  action:
    - service: notify.all
      data:
        message: "Fibaro Smoke Sensor - SMOKE DETECTED!"
    - service: scene.turn_on
      entity_id: scene.bedroom_on
    - service: scene.turn_on
      entity_id: scene.kitchen_on

- alias: Smoke Sensor NOSMOKE
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgss101_smoke_sensor_smoke
    to: '0'
    from: '255'
  action:
    service: notify.all
    data:
      message: "Fibaro Smoke Sensor - Smoke Cleared"

- alias: Smoke Sensor OPENED
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgss101_smoke_sensor_general
    from: '0'
    to: '255'
  action:
    - service: notify.all
      data:
        message: "Fibaro Smoke Sensor - Cover Opened"
    - service: scene.turn_on
      entity_id: scene.bedroom_on
    - service: scene.turn_on
      entity_id: scene.kitchen_on

- alias: Smoke Sensor CLOSED
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgss101_smoke_sensor_general
    to: '0'
    from: '255'
  action:
    - service: notify.all
      data:
        message: "Fibaro Smoke Sensor - Cover Closed"
