- alias: Smoke Sensor SMOKE
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgss101_smoke_sensor_smoke
    to: '255'
  action:
    - service: notify.all
      data:
        message: "Fibaro Smoke Sensor - SMOKE DETECTED!"
    - service: light.turn_on
      data:
        entity_id: group.all_lights
        brightness: 255

- alias: Smoke Sensor NOSMOKE
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgss101_smoke_sensor_smoke
    to: '0'
    from: '255'
  action:
    service: notify.all
    data:
      message: "Fibaro Smoke Sensor - Smoke Cleared"

- alias: Smoke Sensor OPENED
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgss101_smoke_sensor_general
    from: '0'
    to: '255'
  action:
    - service: notify.all
      data:
        message: "Fibaro Smoke Sensor - Cover Opened"

- alias: Smoke Sensor CLOSED
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgss101_smoke_sensor_general
    to: '0'
    from: '255'
  action:
    - service: notify.all
      data:
        message: "Fibaro Smoke Sensor - Cover Closed"
