- alias: "Cold outside"
  trigger:
    - platform: numeric_state
      entity_id: sensor.weather_temperature
      below: 10
  action:
    service: switch.turn_on
    entity_id: switch.climate_normal_mode

- alias: "Normal temperature outside"
 trigger:
   - platform: numeric_state
     entity_id: sensor.weather_temperature
     above: 20
 action:
   service: switch.turn_on
   entity_id: switch.climate_save_mode
